[package]
name = "assignment_29_dec_19"
version = "0.1.0"
authors = ["Invision 016"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"